config/routes.rb
Rails.application.routes.draw do

  get 'categories/index'

  get 'categories/new'

  resources :products
  resources :categories
  resources :product_categories

  root 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_categories
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categorys = Category.all
  end

  def new
    @category  = Category.new
  end

  def show
    @products = Product.joins(:categories).select("*").where(categories: {id: params[:id]})
  end

  def create
    @category  = Category.new(params.require(:category).permit(:name_category))
    if @category.save
      redirect_to categories_path 
    else
      render 'new'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product  = Product.new
  end

  def create
    @product = Product.new(product_categories_params)
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  private
    def product_categories_params
      params.require(:product).permit(:name_product, category_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<%= link_to "Add+",categories_new_path %>

<%= link_to "Products+",products_path %>

<table border="1px">
  <tr>
    <td>Name</td>
  </tr>
  <% @categorys.each do |category| %>
    <tr>
      <td><%= category.name_category  %></td>
      <td>
          <%= link_to 'Delete', category_path(category.id),
          method: :delete,
          data: { confirm: 'Are you sure?' },
          class: "btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/categories/new.html.erb
<%= form_for @category do |f| %>

  <%= f.label :name_category %> <br>
  <%= f.text_field :name_category %>

  <br>
  <%= f.submit %>  

<% end %>

app/views/categories/show.html.erb
<%= link_to "Add+",new_product_path %>

<%= link_to "Category+",categories_path %>

<ul>
  <% Category.all.each do |category| %>
    <li><%= link_to category.name_category , category_path(category.id) %></li>
  <% end %>
</ul>

<table border="1px">
  <tr>
    <td>Name</td>
    <td>Category</td>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name_product  %></td>
      <td><%= product.name_category %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HABTM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<p>Deployed by Codeship habtm-rails fix master  Success</p>
<%= link_to "Add+",new_product_path %>

<%= link_to "Category+",categories_path %>

<ul>
  <% Category.all.each do |category| %>
    <li><%= link_to category.name_category , category_path(category.id) %></li>
  <% end %>
</ul>

<hr>

<table border="1px">
  <tr>
    <td>Name</td>
    <td>Category</td>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name_product  %></td>
      <td>
        <% product.categories.each do |category| %>
          <%= link_to category.name_category ,category_path(category.id)%>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<% @products.each do |product| %>

<% end %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>

  <%= f.label :name_product %> <br>
  <%= f.text_field :name_product %>

  <br>
    <% Category.all.each do |category| %>
      <%= check_box_tag "product[category_ids][]" , category.id %>
      <%= category.name_category %>
       <br>
    <% end %>
  <%= f.submit %>

<% end %>